### ISSUE TITLE
remove print statement

### ISSUE THREAD

**Issue by printf-twinkle** [printf-twinkle/palindrome_check#3]
the code must not have any print statement

**Comment by Prakarsh-Kaushik** [comment]
I would like to contribute to this issue. How may I help?

**Comment by printf-twinkle** [comment]
@Prakarsh-Kaushik I was only testing out something, I will be posting some issues on new repos tomorrow onwards, you may try and solve them, it will be school and basic level!

**Comment by Prakarsh-Kaushik** [comment]
Yes Sure. Thanks for informing
